ci:
  autoupdate_schedule: "quarterly"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: debug-statements
  - id: trailing-whitespace
  - id: check-builtin-literals
  - id: check-executables-have-shebangs
  - id: check-json
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
- repo: https://github.com/asottile/pyupgrade
  rev: 'v3.15.2'
  hooks:
  - id: pyupgrade
    args:
    - --py39-plus